### ISSUE TITLE
Schema::Validator is not flexible

### ISSUE THREAD

**Issue by cyangle** [eliasjpr/contracts#11]
I don't think Schema::Validator is flexible because you can not pass data to it before validating records.

Most other validation libraries store instances of validator classes in the model so that you can pass additional data to it during initialization to customize it's behavior.

**Comment by eliasjpr** [comment]
@cyangle thanks for sharing the issue. 

The intention of the Schema::Validator is to validate an object instance if you need to inject additional data you can set static values. I have not seen the need to inject additional values. This part of the library was inspired by the [Rails Custom Validators](https://guides.rubyonrails.org/active_record_validations.html#custom-validators). 

When creating custom validators you can pass an instance of the object under validation as such. 

```crystal
class UniqueRecordValidator < Schema::Validator
  getter :record, :field, :message

  def initialize(@record : UserModel)
    @field = :email
    @message = "Record must be unique!"
  end

  def valid? : Array(Schema::Error)
    [] of Schema::Error
  end
end
```
