### ISSUE TITLE
Comparison to Amber Params

### ISSUE THREAD

**Issue by jackturnbull** [eliasjpr/contracts#2]
Apologies if I've missed the point of this module but I really like the format - I'd been toying with writing my own JSON Schema validator and then stumbled upon this. It may be a bit of a direct question but as a new user checking out this library, what advantages does this have over using the Amber Params module directly?

Some of the higher level ones I can see:
* Less coupled to the Amber controller
* Predicates without patching base types
* Ability to inspect whole record on each validation

The hope would be to be able to create a set of schemas for each Amber controller and have the schema manage it's own validations without having to rely on the in-built param predicate runner. Is this a valid use case in your eyes?

**Comment by eliasjpr** [comment]
> The hope would be to be able to create a set of schemas for each Amber controller and have the schema manage it's own validations without having to rely on the in-built param predicate runner. Is this a valid use case in your eyes?

Yes, it has long been our desire to decouple the params validation from Amber and use a library for all related validations not only params but al also models and services, clients, etc.  

Ideally we would be able to define a schemas module to use within the APP. I will also help simplify the rendering of JSON and XML payloads with self serializable schemas.
